# Generated by Django 5.0.3 on 2024-03-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('address1', models.CharField(blank=True, null=True)),
                ('address2', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('zip', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('subdomain', models.CharField(blank=True, null=True)),
                ('video', models.CharField(blank=True, null=True)),
                ('retailer_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('menu_type', models.CharField(blank=True, null=True)),
                ('brand', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('pos_id', models.CharField(blank=True, null=True)),
                ('potency_cbd', models.JSONField(blank=True, null=True)),
                ('potency_thc', models.JSONField(blank=True, null=True)),
                ('staff_pick', models.BooleanField(blank=True, null=True)),
                ('strain_type', models.CharField(blank=True, null=True)),
                ('subcategory', models.CharField(blank=True, null=True)),
                ('variants', models.JSONField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, null=True)),
                ('title_tag', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sort', models.FloatField(blank=True, null=True)),
                ('terpenes', models.JSONField(blank=True, null=True)),
                ('custom_section', models.CharField(blank=True, null=True)),
                ('retailer_id', models.CharField(blank=True, null=True)),
                ('sale_type', models.CharField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('dutchie_id', models.CharField(blank=True, null=True)),
                ('enterprise_product_id', models.CharField(blank=True, null=True)),
                ('internal_id', models.CharField(blank=True, null=True)),
                ('sync_date', models.DateTimeField(blank=True, null=True)),
                ('onsale', models.BooleanField(blank=True, null=True)),
                ('cultivar_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='MenuSales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('promo_id', models.CharField(blank=True, null=True)),
                ('menu_id', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('menu_type', models.CharField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu_sales',
            },
        ),
        migrations.CreateModel(
            name='PromoHeaders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, null=True)),
                ('mobile_image', models.CharField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('menu_type', models.CharField(blank=True, null=True)),
                ('external_url', models.CharField(blank=True, null=True)),
                ('mobile_app_image', models.CharField(blank=True, null=True)),
                ('sort_order', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'promo_headers',
            },
        ),
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('menu_type', models.CharField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('image', models.CharField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dutchie_id', models.CharField(blank=True, null=True)),
                ('days', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'promos',
            },
        ),
    ]
